/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author mcv26
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        disableBtn = new javax.swing.JButton();
        serverEnableBtn = new javax.swing.JButton();
        disableServerBtn = new javax.swing.JButton();
        binLabel = new javax.swing.JLabel();
        telLabel = new javax.swing.JLabel();
        claveLabel = new javax.swing.JLabel();
        trasLabel = new javax.swing.JLabel();
        vigenereLabel = new javax.swing.JLabel();
        binCheck = new javax.swing.JCheckBox();
        telCheck = new javax.swing.JCheckBox();
        claveCheck = new javax.swing.JCheckBox();
        trasCheck = new javax.swing.JCheckBox();
        viginereCheck = new javax.swing.JCheckBox();
        reloadButton = new javax.swing.JButton();
        alfaLabel = new javax.swing.JLabel();
        algServer = new javax.swing.JLabel();
        serverLog = new javax.swing.JLabel();
        logLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloLabel.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(243, 126, 11));
        tituloLabel.setText("Administrador de Sistema");

        addBtn.setBackground(new java.awt.Color(51, 204, 255));
        addBtn.setFont(new java.awt.Font("Trajan Pro", 2, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(153, 153, 0));
        addBtn.setText("Agregar");

        disableBtn.setBackground(new java.awt.Color(51, 204, 255));
        disableBtn.setFont(new java.awt.Font("Trajan Pro", 2, 18)); // NOI18N
        disableBtn.setForeground(new java.awt.Color(153, 153, 0));
        disableBtn.setText("Desactivar");
        disableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disableBtnActionPerformed(evt);
            }
        });

        serverEnableBtn.setBackground(new java.awt.Color(51, 204, 255));
        serverEnableBtn.setFont(new java.awt.Font("Trajan Pro", 2, 18)); // NOI18N
        serverEnableBtn.setForeground(new java.awt.Color(153, 153, 0));
        serverEnableBtn.setText("Start Server");

        disableServerBtn.setBackground(new java.awt.Color(51, 204, 255));
        disableServerBtn.setFont(new java.awt.Font("Trajan Pro", 2, 18)); // NOI18N
        disableServerBtn.setForeground(new java.awt.Color(153, 153, 0));
        disableServerBtn.setText("Stop Server");
        disableServerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disableServerBtnActionPerformed(evt);
            }
        });

        binLabel.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        binLabel.setText("Codificación Binaria");

        telLabel.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        telLabel.setText("Codigo Telefonico");

        claveLabel.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        claveLabel.setText("Palabra Clave");

        trasLabel.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        trasLabel.setText("Trasposicion");

        vigenereLabel.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        vigenereLabel.setText("Vigenere");

        binCheck.setFont(new java.awt.Font("Trajan Pro", 2, 12)); // NOI18N
        binCheck.setText("Enable");

        telCheck.setFont(new java.awt.Font("Trajan Pro", 2, 12)); // NOI18N
        telCheck.setText("Enable");

        claveCheck.setFont(new java.awt.Font("Trajan Pro", 2, 12)); // NOI18N
        claveCheck.setText("Enable");

        trasCheck.setFont(new java.awt.Font("Trajan Pro", 2, 12)); // NOI18N
        trasCheck.setText("Enable");

        viginereCheck.setFont(new java.awt.Font("Trajan Pro", 2, 12)); // NOI18N
        viginereCheck.setText("Enable");

        reloadButton.setBackground(new java.awt.Color(51, 204, 255));
        reloadButton.setFont(new java.awt.Font("Trajan Pro", 2, 18)); // NOI18N
        reloadButton.setForeground(new java.awt.Color(153, 153, 0));
        reloadButton.setText("Reload");

        alfaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alfaLabel.setForeground(new java.awt.Color(153, 153, 0));
        alfaLabel.setText("Alfabetos");

        algServer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        algServer.setForeground(new java.awt.Color(153, 153, 0));
        algServer.setText("Algoritmos");

        serverLog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        serverLog.setForeground(new java.awt.Color(153, 153, 0));
        serverLog.setText("Servidor");

        logLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logLabel.setForeground(new java.awt.Color(153, 153, 0));
        logLabel.setText("Logs");

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setFont(new java.awt.Font("Trajan Pro", 2, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 0));
        jButton1.setText("Abrir Carpeta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reloadButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(binLabel)
                                    .addComponent(telLabel)
                                    .addComponent(claveLabel)
                                    .addComponent(trasLabel)
                                    .addComponent(vigenereLabel))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viginereCheck)
                                    .addComponent(trasCheck)
                                    .addComponent(claveCheck)
                                    .addComponent(binCheck)
                                    .addComponent(telCheck)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(addBtn)
                                .addGap(78, 78, 78)
                                .addComponent(disableBtn)))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(serverEnableBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(disableServerBtn)
                        .addGap(29, 29, 29))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alfaLabel)
                            .addComponent(algServer)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1))
                    .addComponent(logLabel)
                    .addComponent(serverLog))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel)
                .addGap(12, 12, 12)
                .addComponent(alfaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(disableBtn))
                .addGap(16, 16, 16)
                .addComponent(algServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(binLabel)
                    .addComponent(binCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telLabel)
                    .addComponent(telCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(claveLabel)
                    .addComponent(claveCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trasLabel)
                    .addComponent(trasCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vigenereLabel)
                    .addComponent(viginereCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reloadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(serverLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverEnableBtn)
                    .addComponent(disableServerBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disableBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disableBtnActionPerformed

    private void disableServerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disableServerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disableServerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel alfaLabel;
    private javax.swing.JLabel algServer;
    private javax.swing.JCheckBox binCheck;
    private javax.swing.JLabel binLabel;
    private javax.swing.JCheckBox claveCheck;
    private javax.swing.JLabel claveLabel;
    private javax.swing.JButton disableBtn;
    private javax.swing.JButton disableServerBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel logLabel;
    private javax.swing.JButton reloadButton;
    private javax.swing.JButton serverEnableBtn;
    private javax.swing.JLabel serverLog;
    private javax.swing.JCheckBox telCheck;
    private javax.swing.JLabel telLabel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JCheckBox trasCheck;
    private javax.swing.JLabel trasLabel;
    private javax.swing.JLabel vigenereLabel;
    private javax.swing.JCheckBox viginereCheck;
    // End of variables declaration//GEN-END:variables
}
