/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author mcv26
 */
import Model.*;
import Servidor.Servidor;
import java.util.ArrayList;
import java.io.*;
import java.lang.reflect.Constructor;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    private Algoritmo newAlgoritmo;
    private final File folder = new File("../Codificador/src/Model");
    
    private void llenadoAlgoritmos(){
        for(File algoritmo : folder.listFiles()){
            if(algoritmo.isFile()){
                if(algoritmo.getName().startsWith("alg")){
                    int largo = algoritmo.getName().length();
                    algoritmosCombo.addItem(algoritmo.getName().substring(3, largo-5));
                }
            }
        }
    }
    
    private void setCheckBox(Algoritmo algoritmo){
        estadoAlgoritmoCheck.setSelected(algoritmo.getEstado());
    }
    
    public Administrador() {
        initComponents();
        llenadoAlgoritmos();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        editAlfaBtn = new javax.swing.JButton();
        serverEnableBtn = new javax.swing.JButton();
        disableServerBtn = new javax.swing.JButton();
        estadoAlgoritmoCheck = new javax.swing.JCheckBox();
        changeButton = new javax.swing.JButton();
        alfaLabel = new javax.swing.JLabel();
        algServer = new javax.swing.JLabel();
        serverLog = new javax.swing.JLabel();
        logLabel = new javax.swing.JLabel();
        abrirLogsBtn = new javax.swing.JButton();
        algoritmosCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloLabel.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(243, 126, 11));
        tituloLabel.setText("Administrador de Sistema");

        addBtn.setBackground(new java.awt.Color(51, 204, 255));
        addBtn.setFont(new java.awt.Font("Trajan Pro", 2, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(153, 153, 0));
        addBtn.setText("Agregar");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editAlfaBtn.setBackground(new java.awt.Color(51, 204, 255));
        editAlfaBtn.setFont(new java.awt.Font("Trajan Pro", 2, 18)); // NOI18N
        editAlfaBtn.setForeground(new java.awt.Color(153, 153, 0));
        editAlfaBtn.setText("Editar/Eliminar");
        editAlfaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAlfaBtnActionPerformed(evt);
            }
        });

        serverEnableBtn.setBackground(new java.awt.Color(51, 204, 255));
        serverEnableBtn.setFont(new java.awt.Font("Trajan Pro", 2, 18)); // NOI18N
        serverEnableBtn.setForeground(new java.awt.Color(153, 153, 0));
        serverEnableBtn.setText("Iniciar Server");
        serverEnableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverEnableBtnActionPerformed(evt);
            }
        });

        disableServerBtn.setBackground(new java.awt.Color(51, 204, 255));
        disableServerBtn.setFont(new java.awt.Font("Trajan Pro", 2, 18)); // NOI18N
        disableServerBtn.setForeground(new java.awt.Color(153, 153, 0));
        disableServerBtn.setText("Detener Server");
        disableServerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableServerBtnMouseClicked(evt);
            }
        });
        disableServerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disableServerBtnActionPerformed(evt);
            }
        });

        estadoAlgoritmoCheck.setFont(new java.awt.Font("Trajan Pro", 2, 14)); // NOI18N
        estadoAlgoritmoCheck.setText("Enable");
        estadoAlgoritmoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoAlgoritmoCheckActionPerformed(evt);
            }
        });

        changeButton.setBackground(new java.awt.Color(51, 204, 255));
        changeButton.setFont(new java.awt.Font("Trajan Pro", 2, 18)); // NOI18N
        changeButton.setForeground(new java.awt.Color(153, 153, 0));
        changeButton.setText("Cambio Estado");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        alfaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alfaLabel.setForeground(new java.awt.Color(153, 153, 0));
        alfaLabel.setText("Alfabetos");

        algServer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        algServer.setForeground(new java.awt.Color(153, 153, 0));
        algServer.setText("Algoritmos");

        serverLog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        serverLog.setForeground(new java.awt.Color(153, 153, 0));
        serverLog.setText("Servidor");

        logLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logLabel.setForeground(new java.awt.Color(153, 153, 0));
        logLabel.setText("Logs");

        abrirLogsBtn.setBackground(new java.awt.Color(51, 204, 255));
        abrirLogsBtn.setFont(new java.awt.Font("Trajan Pro", 2, 18)); // NOI18N
        abrirLogsBtn.setForeground(new java.awt.Color(153, 153, 0));
        abrirLogsBtn.setText("Abrir Carpeta");
        abrirLogsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirLogsBtnActionPerformed(evt);
            }
        });

        algoritmosCombo.setFont(new java.awt.Font("Trajan Pro", 2, 18)); // NOI18N
        algoritmosCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algoritmosComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(addBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editAlfaBtn)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(abrirLogsBtn))
                    .addComponent(logLabel)
                    .addComponent(serverLog))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alfaLabel)
                            .addComponent(algServer))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(changeButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(algoritmosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(estadoAlgoritmoCheck)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(serverEnableBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(disableServerBtn)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel)
                .addGap(12, 12, 12)
                .addComponent(alfaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(editAlfaBtn))
                .addGap(16, 16, 16)
                .addComponent(algServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(algoritmosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoAlgoritmoCheck))
                .addGap(18, 18, 18)
                .addComponent(changeButton)
                .addGap(95, 95, 95)
                .addComponent(serverLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverEnableBtn)
                    .addComponent(disableServerBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abrirLogsBtn)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editAlfaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAlfaBtnActionPerformed
        modificacionAlfabetos nuevo = new modificacionAlfabetos(this);
        nuevo.setVisible(true);
        this.setEnabled(false);
        this.setVisible(false);
    }//GEN-LAST:event_editAlfaBtnActionPerformed

    private void disableServerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disableServerBtnActionPerformed
        // TODO add your handling code here:
        Servidor.getInstance().cambiarEstadoServer();
    }//GEN-LAST:event_disableServerBtnActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        //bin.setEstado(estadoAlgoritmoCheck.isSelected());
    }//GEN-LAST:event_changeButtonActionPerformed

    private void abrirLogsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirLogsBtnActionPerformed
        Runtime r = Runtime.getRuntime();
		Process p = null;

		try {
			p = r.exec("explorer.exe ..\\Codificador\\Logs");
		} catch (Exception e) {
			System.out.println("Error al ejecutar");
		}
    }//GEN-LAST:event_abrirLogsBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        manejoAlfabetos nuevo = new manejoAlfabetos(this);
        nuevo.setVisible(true);
        this.setEnabled(false);
        this.setVisible(false);
    }//GEN-LAST:event_addBtnActionPerformed

    private void serverEnableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverEnableBtnActionPerformed
        // TODO add your handling code here:
        //Servidor.getInstance().iniciarServidor(); //iniciar server sin usar hilos y no sirve, se congela
        Servidor.getInstance().iniciar();           //iniciar server usando hilos
        //System.out.println("paso de iniciar");
    }//GEN-LAST:event_serverEnableBtnActionPerformed

    private void disableServerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableServerBtnMouseClicked
        // TODO add your handling code here:
        //Servidor.getInstance().cambiarEstadoServer();
    }//GEN-LAST:event_disableServerBtnMouseClicked

    private void algoritmosComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algoritmosComboActionPerformed
        String nombre = "Model.alg"+algoritmosCombo.getSelectedItem(); 
        Class newClass;
        try {
            newClass = Class.forName(nombre);
            Constructor creador = newClass.getConstructor(new Class[] {});
            newAlgoritmo = (Algoritmo)creador.newInstance();
            estadoAlgoritmoCheck.setSelected(newAlgoritmo.getEstado());
        } catch (Exception ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_algoritmosComboActionPerformed

    private void estadoAlgoritmoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoAlgoritmoCheckActionPerformed
        newAlgoritmo.setEstado(estadoAlgoritmoCheck.isSelected());
    }//GEN-LAST:event_estadoAlgoritmoCheckActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirLogsBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel alfaLabel;
    private javax.swing.JLabel algServer;
    private javax.swing.JComboBox<String> algoritmosCombo;
    private javax.swing.JButton changeButton;
    private javax.swing.JButton disableServerBtn;
    private javax.swing.JButton editAlfaBtn;
    private javax.swing.JCheckBox estadoAlgoritmoCheck;
    private javax.swing.JLabel logLabel;
    private javax.swing.JButton serverEnableBtn;
    private javax.swing.JLabel serverLog;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
