/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author mcv26
 */
public class manejoAlfabetos extends javax.swing.JPanel {

    /**
     * Creates new form manejoAlfabetos
     */
    public manejoAlfabetos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aceptarBtn = new javax.swing.JButton();
        atrasBtn = new javax.swing.JButton();
        tituloLabel = new javax.swing.JLabel();
        IDText = new javax.swing.JTextField();
        nombreText = new javax.swing.JTextField();
        comboEstado = new javax.swing.JComboBox<>();
        alfabetoText = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        nomLabel = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        alfabetoLabel = new javax.swing.JLabel();

        aceptarBtn.setBackground(new java.awt.Color(51, 204, 255));
        aceptarBtn.setFont(new java.awt.Font("Trajan Pro", 2, 18)); // NOI18N
        aceptarBtn.setForeground(new java.awt.Color(153, 153, 0));
        aceptarBtn.setText("Aceptar");

        atrasBtn.setBackground(new java.awt.Color(51, 204, 255));
        atrasBtn.setFont(new java.awt.Font("Trajan Pro", 2, 18)); // NOI18N
        atrasBtn.setForeground(new java.awt.Color(153, 153, 0));
        atrasBtn.setText("Atrás");

        tituloLabel.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(243, 126, 11));
        tituloLabel.setText("Agregar un Nuevo Alfabeto");

        comboEstado.setBackground(new java.awt.Color(51, 204, 255));
        comboEstado.setFont(new java.awt.Font("Trajan Pro", 3, 12)); // NOI18N
        comboEstado.setForeground(new java.awt.Color(153, 153, 0));
        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activado", "Desactivado" }));
        comboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstadoActionPerformed(evt);
            }
        });

        alfabetoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alfabetoTextActionPerformed(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(153, 153, 0));
        idLabel.setText("Identificador");

        nomLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomLabel.setForeground(new java.awt.Color(153, 153, 0));
        nomLabel.setText("Nombre");

        estadoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        estadoLabel.setForeground(new java.awt.Color(153, 153, 0));
        estadoLabel.setText("Estado");

        alfabetoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alfabetoLabel.setForeground(new java.awt.Color(153, 153, 0));
        alfabetoLabel.setText("Alfabeto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alfabetoText)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alfabetoLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IDText)
                    .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomLabel)
                    .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estadoLabel)
                    .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloLabel)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(atrasBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aceptarBtn)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(nomLabel)
                    .addComponent(estadoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEstado))
                .addGap(8, 8, 8)
                .addComponent(alfabetoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alfabetoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarBtn)
                    .addComponent(atrasBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void alfabetoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alfabetoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alfabetoTextActionPerformed

    private void comboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEstadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDText;
    private javax.swing.JButton aceptarBtn;
    private javax.swing.JLabel alfabetoLabel;
    private javax.swing.JTextField alfabetoText;
    private javax.swing.JButton atrasBtn;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JTextField nombreText;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
