/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static View.main.daoAlfabetos;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mcv26
 */
public class manejoAlfabetos extends javax.swing.JFrame {

    /**
     * Creates new form manejoAlfabetos
     */
    Administrador ventana;
    public manejoAlfabetos(Administrador ventana) {
        this.ventana = ventana;
        initComponents();
    }

     private void cierreVentana(){
        this.setEnabled(false);
        this.setVisible(false);
        ventana.setEnabled(true);
        ventana.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        nomLabel = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        IDText = new javax.swing.JTextField();
        estadoLabel = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox<>();
        alfabetoText = new javax.swing.JTextField();
        alfabetoLabel = new javax.swing.JLabel();
        atrasBtn = new javax.swing.JButton();
        aceptarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(153, 153, 0));
        idLabel.setText("Identificador");

        tituloLabel.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(243, 126, 11));
        tituloLabel.setText("Agregar un Nuevo Alfabeto");

        nomLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomLabel.setForeground(new java.awt.Color(153, 153, 0));
        nomLabel.setText("Nombre");

        estadoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        estadoLabel.setForeground(new java.awt.Color(153, 153, 0));
        estadoLabel.setText("Estado");

        comboEstado.setBackground(new java.awt.Color(51, 204, 255));
        comboEstado.setFont(new java.awt.Font("Trajan Pro", 3, 12)); // NOI18N
        comboEstado.setForeground(new java.awt.Color(153, 153, 0));
        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activado", "Desactivado" }));

        alfabetoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alfabetoLabel.setForeground(new java.awt.Color(153, 153, 0));
        alfabetoLabel.setText("Alfabeto");

        atrasBtn.setBackground(new java.awt.Color(51, 204, 255));
        atrasBtn.setFont(new java.awt.Font("Trajan Pro", 2, 18)); // NOI18N
        atrasBtn.setForeground(new java.awt.Color(153, 153, 0));
        atrasBtn.setText("Atrás");
        atrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBtnActionPerformed(evt);
            }
        });

        aceptarBtn.setBackground(new java.awt.Color(51, 204, 255));
        aceptarBtn.setFont(new java.awt.Font("Trajan Pro", 2, 18)); // NOI18N
        aceptarBtn.setForeground(new java.awt.Color(153, 153, 0));
        aceptarBtn.setText("Aceptar");
        aceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alfabetoText)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alfabetoLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IDText)
                    .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomLabel)
                    .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estadoLabel)
                    .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloLabel)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(atrasBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aceptarBtn)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(nomLabel)
                    .addComponent(estadoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboEstado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(alfabetoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alfabetoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarBtn)
                    .addComponent(atrasBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBtnActionPerformed
        cierreVentana();
    }//GEN-LAST:event_atrasBtnActionPerformed

    private void aceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBtnActionPerformed
        // TODO add your handling code here:
        boolean estado;
        String nombre;
        int indentificador;
        ArrayList<String> listaSimbolos = new ArrayList<>();
        if("Activado".equals((String)comboEstado.getSelectedItem())){
            estado = true;
        }else{
            estado = false;
        }
        nombre = nombreText.getText();
        indentificador = Integer.parseInt(IDText.getText());
        String[] lista = alfabetoText.getText().split(" ");
        if("Activado".equals((String)comboEstado.getSelectedItem())){
            estado = true;
        }else{
            estado = false;
        }
        for (int i = 0; i <lista.length; i++) {
            if(lista[i]!=" "){
                listaSimbolos.add(lista[i]);
            }
        } 
        if(daoAlfabetos.crearAlfabeto(indentificador, nombre, estado, listaSimbolos)){
            JOptionPane.showMessageDialog(null,"El alfabeto fue agregado",
                    "AVISO",JOptionPane.INFORMATION_MESSAGE);
            daoAlfabetos.guardarAlfabetos();
        }else{
            JOptionPane.showMessageDialog(null,"El nombre o identificador estan repetidos",
                    "ERROR",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_aceptarBtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        cierreVentana();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cierreVentana();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDText;
    private javax.swing.JButton aceptarBtn;
    private javax.swing.JLabel alfabetoLabel;
    private javax.swing.JTextField alfabetoText;
    private javax.swing.JButton atrasBtn;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JTextField nombreText;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
